site_name: Fastack
repo_url: https://github.com/fastack-dev/fastack
repo_name: fastack-dev/fastack
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2021 Aprila Hijriyan
plugins:
  - search
  - git-revision-date
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
  - mkdocstrings:
      watch:
        - fastack/
  - include_dir_to_nav

theme:
  name: material
  language: en
  features:
    - navigation.indexes
    - navigation.tracking
    # - toc.integrate
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github
  font:
    text: Open Sans

  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/apriladev

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apriladev

    - icon: fontawesome/brands/medium
      link: https://apriladev.medium.com

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/apriladev/

  alternate:
    - name: English
      link: /
      lang: en

    # - name: Indonesia
    #   link: /id/
    #   lang: id

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - installation.md
  - Getting Started:
    - tutorial/introduction.md
    - tutorial/controller.md
    - tutorial/middleware.md
    - tutorial/globalvariables.md
    - tutorial/cli.md
    - tutorial/plugins.md

  - deployment.md
  - plugins.md
  - contributing.md
  - support.md
  - "API Reference": api
