name: Codecov

on: [push, pull_request]

jobs:
  run:
    name: Coverage test on ${{ matrix.os }} for python v${{ matrix.py }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        py:
          - "3.9"
          - "3.8"
          - "3.7"

    steps:
    - uses: actions/checkout@v2
    - name: Setup python v${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}

    - name: Generate coverage report
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install -vvv --no-dev
        pytest -v --cov=fastack/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        name: codecov-fastack
