# This is a basic workflow to help you get started with Actions

name: Upload Python Package

on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test v${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        py:
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup python v${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - name: Install poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install -vvv

      - name: Tests
        run: pytest -v

  # This workflow contains a single job called "build"
  build:
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload package
        uses: JRubics/poetry-publish@v1.7
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
